package visao.frmproduto;

import java.util.ArrayList;
import modelo.Produto;
import javax.swing.JOptionPane;
import socket.EstoqueCliente;
import visao.Mensagem;

/**
 * Formulário para cadastro de produtos
 *
 */
public class FrmCadastroProduto extends javax.swing.JFrame {

    private Produto objetoproduto;

    /**
     * Construtor do formulário de cadastro de produtos
     */
    public FrmCadastroProduto() {
        initComponents();
        this.objetoproduto = new Produto();
        carregarCategorias();
    }

    /**
     * Carrega as categorias disponíveis no combobox
     */
    private void carregarCategorias() {
        try {
            socket.EstoqueCliente cliente = new socket.EstoqueCliente("localhost", 12345);
            ArrayList<modelo.Categoria> lista = cliente.listarCategorias();

            JCBCategoria.removeAllItems();
            JCBCategoria.addItem("Selecione uma categoria");

            for (modelo.Categoria c : lista) {
                JCBCategoria.addItem(c.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar categorias: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFproduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFpreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFquantidade = new javax.swing.JTextField();
        JBCancelar = new javax.swing.JButton();
        JBCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JTFestoquemaximo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFestoqueminimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JCBCategoria = new javax.swing.JComboBox<>();
        JCBUnidade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setText("Produto:");

        JTFproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprodutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Quantidade:");

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBCadastrar.setText("Cadastrar");
        JBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque Máximo");

        jLabel6.setText("Estoque Mínima:");

        jLabel7.setText("Unidade:");

        JCBUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "g", "Ml", "L" }));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel8.setText("Cadastro Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JTFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JTFestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(JBCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(JBCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTFestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addComponent(JTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(JTFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(JTFestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(JTFestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelar)
                    .addComponent(JBCadastrar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastrarActionPerformed
        try {
            String produto = "";
            double preco = 0;
            String unidade = "";
            String categoria = "";
            int quantidade = 0;
            int estoqueminimo = 25;
            int estoquemaximo = 100;

            // Validação do nome do produto
            if (this.JTFproduto.getText().length() < 2) {
                throw new Mensagem("Produto deve conter ao menos 2 caracteres.");
            } else {
                produto = this.JTFproduto.getText().trim();
            }

            // Validação do preço
            if (this.JTFpreco.getText().isEmpty()) {
                throw new Mensagem("Preço deve ser informado.");
            } else {
                try {
                    String precoStr = this.JTFpreco.getText().replace(",", ".");
                    preco = Double.parseDouble(precoStr);
                    if (preco <= 0) {
                        throw new Mensagem("Preço deve ser maior que zero.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Preço deve ser um número válido (ex: 10.50 ou 10,50).");
                }
            }

            // Validação da unidade
            if (this.JCBUnidade.getSelectedIndex() == -1) {
                throw new Mensagem("Selecione uma unidade.");
            } else {
                unidade = this.JCBUnidade.getSelectedItem().toString();
            }

            // Validação da categoria
            if (this.JCBCategoria.getSelectedIndex() < 1) {
                throw new Mensagem("Selecione uma categoria válida.");
            } else {
                categoria = this.JCBCategoria.getSelectedItem().toString();
            }

            // Validação da quantidade
            if (this.JTFquantidade.getText().isEmpty()) {
                throw new Mensagem("Quantidade deve ser informada.");
            } else {
                try {
                    quantidade = Integer.parseInt(this.JTFquantidade.getText().trim());
                    if (quantidade < 0) {
                        throw new Mensagem("Quantidade não pode ser negativa.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Quantidade deve ser um número válido.");
                }
            }

            // Validação do estoque máximo
            if (this.JTFestoquemaximo.getText().isEmpty()) {
                throw new Mensagem("Quantidade máxima deve ser informada.");
            } else {
                try {
                    estoquemaximo = Integer.parseInt(this.JTFestoquemaximo.getText().trim());
                    if (estoquemaximo <= 0) {
                        throw new Mensagem("Quantidade máxima deve ser maior que zero.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Quantidade máxima deve ser um número válido.");
                }
            }

            // Validação do estoque mínimo
            if (this.JTFestoqueminimo.getText().isEmpty()) {
                throw new Mensagem("Quantidade mínima deve ser informada.");
            } else {
                try {
                    estoqueminimo = Integer.parseInt(this.JTFestoqueminimo.getText().trim());
                    if (estoqueminimo < 0) {
                        throw new Mensagem("Quantidade mínima não pode ser negativa.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Quantidade mínima deve ser um número válido.");
                }
            }

            // Validações adicionais
            if (estoqueminimo >= estoquemaximo) {
                throw new Mensagem("Quantidade mínima deve ser menor que a máxima.");
            }

            if (quantidade < estoqueminimo) {
                int resposta = JOptionPane.showConfirmDialog(null,
                        "Quantidade atual está abaixo do mínimo permitido.\nDeseja continuar mesmo assim?",
                        "Aviso", JOptionPane.YES_NO_OPTION);
                if (resposta != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            // Criar o produto
            Produto novoProduto = new Produto(0, produto, preco, unidade, categoria, quantidade, estoqueminimo, estoquemaximo);

            if (novoProduto.getUnidade() == null || novoProduto.getUnidade().isEmpty()) {
                novoProduto.setUnidade(unidade);
            }

            EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
            String resultado = cliente.inserirProduto(novoProduto);

            if (resultado != null && (resultado.contains("Sucesso") || resultado.contains("sucesso"))) {
                JOptionPane.showMessageDialog(null, "Produto Cadastrado com Sucesso!");

                // Limpar campos
                this.JTFproduto.setText("");
                this.JTFpreco.setText("");
                this.JCBUnidade.setSelectedIndex(0);
                this.JCBCategoria.setSelectedIndex(0);
                this.JTFquantidade.setText("");
                this.JTFestoqueminimo.setText("");
                this.JTFestoquemaximo.setText("");

                carregarCategorias();
                this.dispose();

            } else {
                throw new Mensagem("Erro no servidor: " + (resultado != null ? resultado : "Resposta nula"));
            }

        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (Exception erro2) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado: " + erro2.getMessage());
        }
    }//GEN-LAST:event_JBCadastrarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTFprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprodutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCadastrar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JComboBox<String> JCBCategoria;
    private javax.swing.JComboBox<String> JCBUnidade;
    private javax.swing.JTextField JTFestoquemaximo;
    private javax.swing.JTextField JTFestoqueminimo;
    private javax.swing.JTextField JTFpreco;
    private javax.swing.JTextField JTFproduto;
    private javax.swing.JTextField JTFquantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
