package visao.frmproduto;

import modelo.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import socket.EstoqueCliente;
import visao.Mensagem;

/**
 * Formulário para gerenciamento de produtos
 */
public class FrmGerenciaProduto extends javax.swing.JFrame {

    private Produto objetoproduto;

    /**
     * Construtor do formulário de gerenciamento de produtos
     */
    public FrmGerenciaProduto() {
        initComponents();
        this.objetoproduto = new Produto();
        this.carregaTabela();
        carregarCategorias();
    }

    /**
     * Carrega os dados na tabela de produtos
     */
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableProduto.getModel();
        modelo.setNumRows(0);

        try {
            EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
            ArrayList<Produto> minhaLista = cliente.listarProdutos();

            for (Produto p : minhaLista) {
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getProduto(),
                    String.format("R$ %.2f", p.getPreco()),
                    p.getUnidade(),
                    p.getCategoria(),
                    p.getQuantidade(),
                    p.getEstoqueminimo(),
                    p.getEstoquemaximo()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
        }
    }

    /**
     * Carrega as categorias disponíveis no combobox
     */
    private void carregarCategorias() {
        try {
            JCBCategoria.removeAllItems();
            JCBCategoria.addItem("Selecione uma categoria");

            socket.EstoqueCliente cliente = new socket.EstoqueCliente("localhost", 12345);
            ArrayList<modelo.Categoria> categorias = cliente.listarCategorias();

            for (modelo.Categoria categoria : categorias) {
                JCBCategoria.addItem(categoria.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar categorias: " + e.getMessage());
        }
    }

    /**
     * Atualiza a tabela de produtos
     */
    public void atualizarTabela() {
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTFproduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFpreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFquantidade = new javax.swing.JTextField();
        JBCancelar = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JTFestoquemaximo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFestoqueminimo = new javax.swing.JTextField();
        JBReajuste = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JCBCategoria = new javax.swing.JComboBox<>();
        JCBUnidade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Produtos");

        JTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Preço", "Unidade", "Categoria", "Quantidade", "Estoque Mínimo", "Estoque Máximo"
            }
        ));
        JTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProduto);

        jLabel1.setText("Nome:");

        JTFproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprodutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço:");

        JTFpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprecoActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria:");

        jLabel4.setText("Quantidade:");

        JTFquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFquantidadeActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        Apagar.setText("Apagar");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });

        jLabel5.setText("Estoque Màximo");

        jLabel6.setText("Estoque Mínimo");

        JTFestoqueminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFestoqueminimoActionPerformed(evt);
            }
        });

        JBReajuste.setText("Reajuste");
        JBReajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReajusteActionPerformed(evt);
            }
        });

        jLabel7.setText("Unidade:");

        JCBUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "g", "L", "Ml" }));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel8.setText("Gerencia Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JCBCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JCBUnidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JTFpreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JTFproduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(JTFestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JTFestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(JBCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBAlterar)
                        .addGap(70, 70, 70)
                        .addComponent(JBReajuste)
                        .addGap(45, 45, 45)
                        .addComponent(Apagar)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTFestoqueminimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFestoquemaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAlterar)
                    .addComponent(JBCancelar)
                    .addComponent(JBReajuste)
                    .addComponent(Apagar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFquantidadeActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        try {
            int id = 0;
            String produto = "";
            double preco = 0;
            String unidade = "";
            String categoria = "";
            int quantidade = 0;

            if (this.JTableProduto.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione um produto para alterar.");
            } else {
                id = Integer.parseInt(this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 0).toString());
            }

            // Validação do nome do produto
            if (this.JTFproduto.getText().length() < 2) {
                throw new Mensagem("Produto deve conter ao menos 2 caracteres.");
            } else {
                produto = this.JTFproduto.getText();
            }

            // CORREÇÃO MELHORADA: Validação do preço
            if (this.JTFpreco.getText().isEmpty()) {
                throw new Mensagem("Preço deve ser informado.");
            } else {
                try {
                    String precoStr = this.JTFpreco.getText().replace(",", ".");
                    preco = Double.parseDouble(precoStr);
                    if (preco <= 0) {
                        throw new Mensagem("Preço deve ser maior que zero.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Preço deve ser um número válido (ex: 10.50 ou 10,50).");
                }
            }

            // Validação da unidade
            if (this.JCBUnidade.getSelectedIndex() == -1) {
                throw new Mensagem("Unidade deve ser selecionada");
            } else {
                unidade = this.JCBUnidade.getSelectedItem().toString();
            }

            // Validação da categoria
            if (this.JCBCategoria.getSelectedIndex() < 1) {
                throw new Mensagem("Selecione uma categoria válida.");
            } else {
                categoria = this.JCBCategoria.getSelectedItem().toString();
            }

            // Validação da quantidade
            if (this.JTFquantidade.getText().isEmpty()) {
                throw new Mensagem("Quantidade deve ser informada.");
            } else {
                try {
                    quantidade = Integer.parseInt(this.JTFquantidade.getText().trim());
                    if (quantidade < 0) {
                        throw new Mensagem("Quantidade não pode ser negativa.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Quantidade deve ser um número válido.");
                }
            }

            // Usar valores fixos para estoque min/max
            int estoqueminimo = 25;
            int estoquemaximo = 100;

            // Avisos
            if (quantidade < estoqueminimo) {
                JOptionPane.showMessageDialog(null,
                        "INFORMAÇÃO: Quantidade atual (" + quantidade + ") está abaixo do mínimo (" + estoqueminimo + ").\n"
                        + "Considere fazer uma reposição de estoque.",
                        "Informação de Estoque",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            if (quantidade > estoquemaximo) {
                JOptionPane.showMessageDialog(null,
                        "INFORMAÇÃO: Quantidade atual (" + quantidade + ") está acima do máximo (" + estoquemaximo + ").\n"
                        + "Considere ajustar o estoque máximo se necessário.",
                        "Informação de Estoque",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            // Executar a alteração
            EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
            Produto produtoAtualizado = new Produto(id, produto, preco, unidade, categoria, quantidade, estoqueminimo, estoquemaximo);
            String resultado = cliente.atualizarProduto(produtoAtualizado);

            if (resultado.contains("Sucesso") || !resultado.contains("Erro")) {
                // Limpar campos
                this.JTFproduto.setText("");
                this.JTFpreco.setText("");
                this.JCBUnidade.setSelectedIndex(0);
                this.JCBCategoria.setSelectedIndex(0);
                this.JTFquantidade.setText("");
                this.JTFestoqueminimo.setText("");
                this.JTFestoquemaximo.setText("");

                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");
            } else {
                throw new Mensagem(resultado);
            }

        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (Exception erro2) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + erro2.getMessage());
        } finally {
            carregaTabela();
        }

    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JTFprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprodutoActionPerformed

    private void JTFprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprecoActionPerformed

    private void JTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProdutoMouseClicked
        if (this.JTableProduto.getSelectedRow() != -1) {
            try {
                // Obter valores da tabela
                String produto = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 1).toString();
                String preco = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 2).toString();
                String unidade = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 3).toString();
                String categoria = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 4).toString();
                String quantidade = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 5).toString();
                String estoqueMinimo = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 6).toString();
                String estoqueMaximo = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 7).toString();

                // CORREÇÃO: Converter o preço para o formato correto
                String precoFormatado = preco;
                if (preco.contains("R$")) {
                    // Remover "R$" e espaços, e substituir vírgula por ponto
                    precoFormatado = preco.replace("R$", "").trim();
                    precoFormatado = precoFormatado.replace(",", ".");
                } // Preencher os campos
                this.JTFproduto.setText(produto);
                this.JTFpreco.setText(precoFormatado); // Usar o preço formatado
                this.JCBUnidade.setSelectedItem(unidade);
                this.JCBCategoria.setSelectedItem(categoria);
                this.JTFquantidade.setText(quantidade);

                // Usar valores fixos para estoque min/max
                this.JTFestoquemaximo.setText("100");
                this.JTFestoqueminimo.setText("25");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados do produto selecionado: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_JTableProdutoMouseClicked

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        try {
            int id = 0;
            if (this.JTableProduto.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro Selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 0).toString());
            }
            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar esse Produto?");
            if (respostaUsuario == 0) {

                EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
                String resultado = cliente.deletarProduto(id);

                if (resultado.toLowerCase().contains("sucesso")) {
                    this.JTFproduto.setText("");
                    this.JTFpreco.setText("");
                    this.JCBUnidade.setSelectedItem("");
                    this.JCBCategoria.setSelectedItem("");
                    this.JTFquantidade.setText("");
                    this.JTFestoqueminimo.setText("");
                    this.JTFestoquemaximo.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Produto Apagado com sucesso!");
                } else {
                    throw new Mensagem(resultado);
                }
            }
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_ApagarActionPerformed

    private void JBReajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReajusteActionPerformed
        try {
            int linhaSelecionada = JTableProduto.getSelectedRow();
            if (linhaSelecionada == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um produto para reajustar o preço");
                return;
            } // Obter o produto selecionado
            int id = (int) JTableProduto.getValueAt(linhaSelecionada, 0);
            String nome = (String) JTableProduto.getValueAt(linhaSelecionada, 1);

            // Obter preço como String e converter para Double
            String precoStr = (String) JTableProduto.getValueAt(linhaSelecionada, 2);
            double precoAtual;

            try {

                precoStr = precoStr.replace("R$", "").trim();
                precoStr = precoStr.replace(".", "").replace(",", ".");
                precoAtual = Double.parseDouble(precoStr);
            } catch (NumberFormatException e) {
                throw new Exception("Erro ao converter preço: " + precoStr + ". Formato esperado: R$ 10,50");
            }

            // Solicitar percentual de reajuste
            String percentualStr = JOptionPane.showInputDialog(this,
                    "Produto: " + nome + "\n"
                    + "Preço atual: R$ " + String.format("%.2f", precoAtual).replace(".", ",") + "\n\n"
                    + "Digite o percentual de reajuste:\n(Ex: 10 para aumento de 10%, -5 para redução de 5%)",
                    "Reajuste de Preço - " + nome,
                    JOptionPane.QUESTION_MESSAGE);

            if (percentualStr == null || percentualStr.trim().isEmpty()) {
                return;
            }

            double percentual = Double.parseDouble(percentualStr);
            double novoPreco = precoAtual * (1 + percentual / 100);
            novoPreco = Math.round(novoPreco * 100.0) / 100.0; // Arredondar para 2 casas decimais

            // Criar produto com novo preço
            Produto produto = new Produto();
            produto.setId(id);
            produto.setPreco(novoPreco);

            // Enviar para o servidor
            EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
            String resultado = cliente.reajustarPrecos(produto);

            JOptionPane.showMessageDialog(this,
                    resultado + "\n\n"
                    + "Preço anterior: R$ " + String.format("%.2f", precoAtual).replace(".", ",") + "\n"
                    + "Novo preço: R$ " + String.format("%.2f", novoPreco).replace(".", ",") + "\n"
                    + "Variação: " + (percentual >= 0 ? "+" : "") + String.format("%.1f", percentual) + "%",
                    "Reajuste Concluído", JOptionPane.INFORMATION_MESSAGE);

            carregaTabela(); // Recarregar tabela para mostrar preço atualizado

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, digite um valor numérico válido para o percentual",
                    "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao reajustar preço: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBReajusteActionPerformed

    private void JTFestoqueminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFestoqueminimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFestoqueminimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBReajuste;
    private javax.swing.JComboBox<String> JCBCategoria;
    private javax.swing.JComboBox<String> JCBUnidade;
    private javax.swing.JTextField JTFestoquemaximo;
    private javax.swing.JTextField JTFestoqueminimo;
    private javax.swing.JTextField JTFpreco;
    private javax.swing.JTextField JTFproduto;
    private javax.swing.JTextField JTFquantidade;
    private javax.swing.JTable JTableProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
