package visao.frmrelatorios;
import modelo.Produto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import socket.EstoqueCliente;

/**
 * Exibe os produtos que estão com quantidade acima da máxima.
 * <p>
 * {@link Produto} fornece a lista de produtos. A classe identifica e lista 
 * todos os que estão com quantidade acima da determinada como máxima no
 * estoque
 * </p>
 */
public class FrmProdutosEstoqueMaximo extends javax.swing.JFrame {

    /** Acessa a lista de produtos */
    private Produto objetoproduto;
    
    /**
     * Construtor padrão
     * Inicializa os componentes e carrega os dados na tabela
     */
    public FrmProdutosEstoqueMaximo() {
       initComponents();
       this.objetoproduto = new Produto();
        this.carregarTabela();
    }
    
    /**
     * Carrega os produtos com quantidade acima do máximo na tabela
     * <p>
     * Filtra a lista de produtos fornecida pelo {@link Produto}
     * </p>
     */
    public void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableRelatorioProdutoMaximo.getModel();
        modelo.setNumRows(0);
        try {
            EstoqueCliente cliente = new EstoqueCliente("localhost", 12345);
            ArrayList<Produto> lista = cliente.relatorioEstoqueMaximo();

            for (Produto produto : lista) {
                modelo.addRow(new Object[]{
                    produto.getId(),
                    produto.getProduto(),
                    produto.getQuantidade(),
                    produto.getEstoquemaximo()
                });
            }

            if (modelo.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Nenhum produto acima do estoque máximo encontrado.",
                        "Informação",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao carregar dados: " + e.getMessage(),
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableRelatorioProdutoMaximo = new javax.swing.JTable();
        JBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableRelatorioProdutoMaximo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Estoque Mínimo", "Estoque Máximo"
            }
        ));
        jScrollPane1.setViewportView(JTableRelatorioProdutoMaximo);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(JBCancelar)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(JBCancelar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Evento de clicar no botão cancelar
     * Fecha a janela atual
     * @param evt Evento de clique no botão
     */
    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * Método principal
     * Inicia a interface
     * @param args the command line arguments (não utilizados)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosEstoqueMaximo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosEstoqueMaximo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosEstoqueMaximo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutosEstoqueMaximo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutosEstoqueMaximo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JTable JTableRelatorioProdutoMaximo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
